-- AI-generated executive summary shown at the top of the dashboard.
-- The most recent row is displayed; regenerated by the ingest pipeline.
create table executive_summaries (
  id           uuid primary key default gen_random_uuid(),
  summary      text not null,
  source       text not null default 'rules',  -- 'ai' | 'rules'
  model        text,                            -- model id when source = 'ai'
  window_note  text,                            -- e.g. "24h activity, 7d trends"
  generated_at timestamptz not null default now(),
  created_at   timestamptz not null default now()
);
create index executive_summaries_generated_at_idx
  on executive_summaries (generated_at desc);

alter table executive_summaries enable row level security;

create policy "allowed read executive_summaries" on executive_summaries
  for select to authenticated using (public.is_allowed_user());

grant select on executive_summaries to authenticated;
grant all privileges on executive_summaries to service_role;
